Movies/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using Movies.Data;
using Movies.Data.Services;
using Movies.Models;

namespace Movies.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;

        public ActorsController(IActorsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        //Get actors/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }
        //Get actors details by id
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }
        //Get Actor Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(int id, Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
        }
        //Get Actor delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Movies/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movies.Data;
using Movies.Data.Services;
using Movies.Models;

namespace Movies.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemaService _Service;
        public CinemasController(ICinemaService service)
        {
            _Service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allcinemas = await _Service.GetAllAsync();
            return View(allcinemas);
        }
        public IActionResult create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> create([Bind("Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            await _Service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Details(int id)
        {
            var cinemaDetails = await _Service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _Service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema);
            await _Service.UpdateAsync(id, cinema);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _Service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinemaDetails = await _Service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            await _Service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Movies/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Movies.Data;
using Microsoft.EntityFrameworkCore;
using Movies.Data.Services;
using Movies.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Movies.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;
        public MoviesController(IMoviesService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allmovies = await _service.GetAllAsync(n => n.Cinema);
            return View(allmovies);
        }
        // below method is to search the movie
        public async Task<IActionResult> Filter(string searchString)
        {
            var allmovies = await _service.GetAllAsync(n => n.Cinema);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allmovies.Where(n => n.Name.ToLower().Contains(searchString)||n.Description.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }
            
            return View("Index", allmovies);
        }
        //get: Movies/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsynch(id);
            return View(movieDetails);
        }
        //Get: Movie/Create
        public async Task<IActionResult> Create()
        {
            var DropdownsData = await _service.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(DropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(DropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(DropdownsData.Actors, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var DropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(DropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(DropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(DropdownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            await _service.AddnewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        //Get: Movie/Edit/1(id)
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsynch(id);
            if (movieDetails == null) return View("NotFound");

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),

            };

            var DropdownsData = await _service.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(DropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(DropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(DropdownsData.Actors, "Id", "FullName");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var DropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(DropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(DropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(DropdownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }
    }
}

Movies/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Movies.Data;
using Movies.Data.Services;
using Movies.Data.ViewModels;
using Movies.Models;

namespace Movies.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;

        }

        public async Task<IActionResult> Index()
        {
            string userId = "";
            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var item = _shoppingCart.GetShoppingcartItems();
            _shoppingCart.ShoppingCartItems = item;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingcartTotal(),
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemsInShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsynch(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveItemsFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsynch(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingcartItems();
            string userId = "";
            string userEmailAddress = "";

            await _ordersService.StoreOrderAsync(items,userId, userEmailAddress);
            await _shoppingCart.ClearshoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

Movies/Views/Shared/NotFound.cshtml
<div class="row text center">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">We are facing some issue, inconvenience is higly regretted</h1>
        <h2 class="text-center">you can check out other movies</h2>
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home page</a>
    </div>

</div>

Movies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movies.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>



                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>

                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-gear">Management</i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"> Cinemas</i></a></li>
                                <li><a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"> Producers</i></a></li>
                                <li><a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-video"> Actors</i></a></li>
                                @*<li><a class="dropdown-item" asp-controller="Orders" asp-action="ShoppingCart"><i class="bi bi-cart"> Orders</i></a></li>*@
                            </ul>
                        </li>
                    </ul>
                </div>

                <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 45px;">
                    <div class="row">
                        <div class="col-md-11">
                            <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        </div>
                        <div class="col-md-1">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                        </div>
                    </div>
                </form>
                <span class="btn btn-sm search"></span>
                <ul class="navbar-nav">
                    @await Component.InvokeAsync("ShoppingCartSummary") @*to show cart with items in it near search bar*@
                </ul>
                @*User Profile section*@
                <div class="dropdown">
                    <button class="btn btn-outline-success dropdown-toggle" href="#" role="button" id="profile-btn" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <i class="bi bi-person-badge"></i>  Hello User
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="profile-btn">
                        <li>
                            <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                                <i class="bi bi-list"></i> Orders
                            </a>
                        </li>
                    </ul>
                </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Movies by Jashan Bhardwaj
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Movies/Views/Shared/_createIteam.cshtml
@model string;
<div style="position:float-right; right:105px; bottom:85px" class="text-end">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i> Add new</a>
</div>